_BASE_: "maskdino_R50_bs16_50ep_3s.yaml"
MODEL:
  WEIGHTS: "../weights/model_0059999.pth"
  SEM_SEG_HEAD:
    NUM_CLASSES: 1
  MaskDINO:
    NUM_OBJECT_QUERIES: 100
DATASETS:
  TRAIN: ()
  TEST: ()
INPUT:
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_detr"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  CROP:
    ENABLED: False
VERSION: 2
